### ISSUE TITLE
Querying a DbSet via LINQ that is Mocked Throws Argument is Not Valid Exception

### ISSUE THREAD

**Issue by ctorx** [MichalJankowskii/Moq.EntityFrameworkCore#11]
I was using ReturnsDbSet in my tests.  The was working fine so long as my queries did not have conditions.  E.g., they looked like this...

`var results = myContext.Set<MyEntity>().ToList();`

Once I added conditons, like so:

`var results = myContext.Set<MyEntity>().Where(x => x.MyCondition == true).ToList();`

It stopped working with the following exception:

`System.ArgumentException: Argument expression is not valid`

The application was not failing, just the test.  

This was using MSTest Framework.

**Comment by MichalJankowskii** [comment]
Is it possible that you will provide both test cases as an example.

Please let me know also which version of lib you are using.

That information will help me with defining your issue.

**Comment by kimcuhoang** [comment]
Hi,
I also meet this issue. After googled, I found some interested information. 
Please see the reported and also suggested solution in the following link below

From [MockQueryable](https://github.com/romantitov/MockQueryable) repository at [comment](https://github.com/romantitov/MockQueryable/issues/17#issuecomment-520480720)
![image](https://user-images.githubusercontent.com/12949191/68178475-bcec9080-ffbe-11e9-8e53-1d1bdd76906a.png)

From [aspnet/EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore) repository at the [comment](https://github.com/aspnet/EntityFrameworkCore/issues/16864#issuecomment-516852769)
![image](https://user-images.githubusercontent.com/12949191/68178598-2d93ad00-ffbf-11e9-836a-64c07611341b.png)

I've made a pull-request at - https://github.com/MichalJankowskii/Moq.EntityFrameworkCore/pull/12

Hope it's useful.

**Comment by SimonWilliams-STL** [comment]
This is causing us a big problem. We have 60 tests that are failing with this since upgrading to DotNet Core 3.0.

**Comment by MichalJankowskii** [comment]
I will accept this when I will have access to pc.

Probably tomorrow.

**Comment by MichalJankowskii** [comment]
Package updated and published

**Comment by ctorx** [comment]
A workaround for anyone who can't upgrade is to use the in memory Entity
Framework context.  Simple add entities to your in memory context and call
save changes as part of your test setup.
