### ISSUE TITLE
Target framework is netstandard2.1

### ISSUE THREAD

**Issue by adrichema** [MichalJankowskii/Moq.EntityFrameworkCore#13]
Why the target framework is netstandard2.1? 

Now it's not possible to use on a .NETcore3.1 project.

Kind regards,

Arthur

**Comment by MichalJankowskii** [comment]
netstandard2.1 was required by EF.core 3.0. 

I will migrate lib to 3.1.x and then I will be able to switch to netstandard2.0.

**Comment by MichalJankowskii** [comment]
Nuget package is already available

**Comment by adrichema** [comment]
Thank you so much Michal, our automated build is working again. Have nice day!
