### ISSUE TITLE
Why is T parameter of ReturnsDbSet restricted to DbContext?

### ISSUE THREAD

**Issue by lenraven** [MichalJankowskii/Moq.EntityFrameworkCore#14]
I have a little problem with the ReturnsDbSet extension method.
I want to use it with an interface, because of the restriction I can not use it.
In my opinion DbContext restriction is unnecessary, a `class` restriction can be enough.

**For example:**
Interface:
```
public interface IBlogContext
{
    DbSet<Post> Posts { get; }
}
```
DbContext:
```
public class BlogContext : DbContext, IBlogContext
{
...
    public DbSet<Post> Posts => Set<Post>();
...
}
```

In this case when I try to use this extension I will get a compilation error.
```
...
var posts = new List<Post>();
...
var contextMock = new Mock<IBlogContext>();
contextMock.Setup(p => p.Posts).ReturnsDbSet(posts);
...
```

**Comment by MichalJankowskii** [comment]
Hi,

I published a new version that does not have mentioned constraint.
