### ISSUE TITLE
Mocking FindAsync seems to not be returning results

### ISSUE THREAD

**Issue by remcobosman** [MichalJankowskii/Moq.EntityFrameworkCore#16]
Dear Michal,

I am trying out your EF  Mocking library, but I am making calls to FindAsync that, I suppose, is not mocked, is that correct? And is it possible to add mocking for this?

Regards,

Remco Bosman

**Comment by MichalJankowskii** [comment]
Hi,

I will summarise our discussion also in issue. Some of it has been published in [pull requests #17](https://github.com/MichalJankowskii/Moq.EntityFrameworkCore/pull/17).

Generally, at first I wanted to add this feature to this lib. Today I think that it is not needed. I created a branch for this case - [FindAsync](https://github.com/MichalJankowskii/Moq.EntityFrameworkCore/tree/FindAsync) where I placed some example to this issue.

In class UsersService I created FindAsync method:
```
public async Task<User> FindAsync(params object[] keyValues)
{
   return await this.usersContext.Users.FindAsync(keyValues);
}
```

To test that you can use existing library and add small additional mocking:
```
[Fact]
public async Task Given_ListOfUser_When_FindAsync_Then_CorrectUserIsReturned()
{
    var users = GenerateNotLockedUsers();
    var userContextMock = new Mock<UsersContext>();
    userContextMock.Setup(m => m.Users.FindAsync(It.IsAny<object[]>())).Returns<object[]>(async (d) => await Task.FromResult(users.FirstOrDefault()));

    var usersService = new UsersService(userContextMock.Object);
    var user = users.FirstOrDefault();

    //Act
    var userToAssert = await usersService.FindAsync(user.Id);

    //Assert
    Assert.Equal(userToAssert, user);
}
```

You need just to customize mock - check if correct parameters are provided to FindAsync and adjusted return.

Please let me know if this will solve your issue.
