### ISSUE TITLE
Version 2.x only returns dbset on first call 

### ISSUE THREAD

**Issue by padraichickey81** [MichalJankowskii/Moq.EntityFrameworkCore#18]
There is a bug with version 2.2.1 which you have fixed in 3.x
Can you apply the fix to a version 2.x of this project?

In this file: https://github.com/MichalJankowskii/Moq.EntityFrameworkCore/blob/ver_2.2.1/src/Moq.EntityFrameworkCore/MoqExtensions.cs 
on line 46:
`dbSetMock.As<IQueryable<TEntity>>().Setup(m => m.GetEnumerator()).Returns(entitiesAsQueryable.GetEnumerator());`

This results in the enumerator returning values on the first call only.

In this files: https://github.com/MichalJankowskii/Moq.EntityFrameworkCore/blob/master/src/Moq.EntityFrameworkCore/MoqExtensions.cs
on line 49 you have fixed the issue.
`dbSetMock.As<IQueryable<TEntity>>().Setup(m => m.GetEnumerator()).Returns(() => entitiesAsQueryable.GetEnumerator());`

We can't use the latest version of this package as we are using version 2.2.6 of Microsoft.EntityFrameworkCore and this package has the following dependencies:
    Microsoft.EntityFrameworkCore (>= 3.1.2)
    Moq (>= 4.13.1)

On a separate note why is there a hard dependency on Moq 4.13.1 and Microsoft.EntityframeworkCore 3.1.2?
As this is being used as a nuget package the project should target the lowest compatible version of it's dependencies.
Else you are forcing all users of this package to upgrade there moq and microsoft efcore versions.

**Comment by MichalJankowskii** [comment]
I will try to solve your issue.

**Comment by MichalJankowskii** [comment]
Fixed in 2.2.1.1 version. It is already on nuget
