### ISSUE TITLE
Make the ReturnsDbSet function an extension of SetupGet for verifications

### ISSUE THREAD

**Issue by LaurentLardenois** [MichalJankowskii/Moq.EntityFrameworkCore#23]
Very cool library which is helpful for making DbContexts properly testable, it just has a small mistake. Since the DbSet is a property it should not be setup in Moq through a Setup call but through a SetupGet call. By doing this you can also verify it has been called, this is not possible currently due to Verify not supporting properties and VerifyGet not matching a Setup call.

**Comment by MichalJankowskii** [comment]
I checked Moq documentation and would say both options are correct. I will add SetupGet as an alternative to lib. So everybody will be able to select a suitable for them approach.
