### ISSUE TITLE
DbSetProxy.Add method always returns null

### ISSUE THREAD

**Issue by vhforte** [MichalJankowskii/Moq.EntityFrameworkCore#25]
DbSetProxy.Add method always returns null.
It is supposed to return Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry instance
with one property - Entity, which is the added entity itself.

Also, not clear how to test dbSet.Add() method.
It looks like the underlyig list of items remains the same after calling dbSet.Add().

```C#
var dbContext = new Mock<IMyContext>(MockBehavior.Strict);
var myList = new List<User>();
dbContext.Setup(o => o.Users).ReturnsDbSet(myList);

var dbSet = ctx.Users;
dbSet.Add(new User());
// myList remains empty, but must have 1 item
```

How can I check if something was Added to the dbSet ?

**Comment by vhforte** [comment]
the ReturnsDbSet() accepts dbSet moq as last parameter. I can setup it for Add, Remove, Update and other methods.

**Comment by MichalJankowskii** [comment]
Great that you manage to solve the issue. I have a crazy week and didn't manage to jump here.
