### ISSUE TITLE
DbContext.Entry<TGeneric>() returns null when using this package

### ISSUE THREAD

**Issue by dkimbell13** [MichalJankowskii/Moq.EntityFrameworkCore#28]
I am wrong in my assumption that the .Entry<TGeneric>() returns null? 

so an attempt to access DbContext.Entry<TGeneric>().State throws a null reference exception?

Is there a way to Moq this method?

**Comment by MichalJankowskii** [comment]
I am not sure what is the issue here. Can you please provide a code? Have you followed the example from the tutorial?
