### ISSUE TITLE
Automapper and ProjectTo

### ISSUE THREAD

**Issue by patryqs** [MichalJankowskii/Moq.EntityFrameworkCore#29]
Unfortunately it doesn't work with **Automapper** and **ProjectTo**.
When I try to use it I get exception:

_System.InvalidCastException: 'Unable to cast object of type 'Moq.EntityFrameworkCore.DbAsyncQueryProvider.InMemoryAsyncEnumerable'1[**MyClass**]' to type 'System.Linq.IQueryable'1[**MyClass**]'.'_

Without **ProjectTo**  everything works fine.

**Comment by MichalJankowskii** [comment]
Could you please provide a code that will reproduce mentioned behaviour? It will help me to diagnose the issue.

**Comment by patryqs** [comment]
Something like this is enough to trigger this error.

```csharp
public async Task<BlogDto> GetBlogs()
{
     var result = await context.Blogs
            .ProjectTo<BlogDto>(_mapper.ConfigurationProvider)
            .ToListAsync();
     return result;
}
```
The same code without ```ProjectTo``` works fine.

The problem is the method ```CreateQuery(Expression expression)``` in ```InMemoryAsyncQueryProvider<TEntity>```.
When I changed it to:
```csharp
        public IQueryable CreateQuery(Expression expression)
        {
            switch (expression)
            {
                case MethodCallExpression m:
                    {
                        var resultType = m.Method.ReturnType; // it shoud be IQueryable<T>
                        var tElement = resultType.GetGenericArguments()[0];
                        var queryType = typeof(InMemoryAsyncEnumerable<>).MakeGenericType(tElement);
                        return (IQueryable)Activator.CreateInstance(queryType, expression);
                    }
            }
            return new InMemoryAsyncEnumerable<TEntity>(expression);
        }
```
everything started working fine.

I found the solution [here](https://stackoverflow.com/a/45769447)

**Comment by MichalJankowskii** [comment]
Thank you for the comment, and sorry for taking a bit longer to get the answer. I needed to find time to check the details.

This is a particular case for me, and I do not want to add code to lib targeting only the Automapper case. 

I am a bit afraid that `Activator.CreateInstance` will cause issues for other people.
