### ISSUE TITLE
Add and RemoveRange methods on returned DbSet didn't work

### ISSUE THREAD

**Issue by LiangZugeng** [MichalJankowskii/Moq.EntityFrameworkCore#3]
We are using the extension and it worked great for querying data, however, Add and RemoveRange methods didn't work as expected on the returned DbSet , we prepared a code repro to demo this, this may be due to our insufficient understandings on Moq internals so we couldn't prepare the data or did the setup correctly, please help take a look, it is greatly appreciated if you can give us some suggestions.

We simply fork your code and modified the sample code and added two test cases, the first case failed [here](https://github.com/LiangZugeng/Moq.EntityFrameworkCore/blob/dfa6dfb46b8f3ebca468b60b0e26685d29ddb16a/src/Moq.EntityFrameworkCore.Examples/UsersServiceTest.cs#L33), the second case failed [here](https://github.com/LiangZugeng/Moq.EntityFrameworkCore/blob/dfa6dfb46b8f3ebca468b60b0e26685d29ddb16a/src/Moq.EntityFrameworkCore.Examples/UsersServiceTest.cs#L53).

Again we appreciate any help you may offer.

**Comment by MichalJankowskii** [comment]
Please remember that this library helps you with setting up the mock. It is not simulating all EF actions in memory. 

In your test case, you should use another approach. Please find the example for AddUser:
```csharp
// Arrange
var user = Fixture.Build<User>().Create();
var usersDb = new Mock<DbSet<User>>();
var usersContextMock = new Mock<UsersContext>();
usersContextMock.Setup(x => x.Users).Returns(usersDb.Object);
var usersService = new UsersService(usersContextMock.Object);

// Act
usersService.AddUser(user);

// Assert
usersDb.Verify(x => x.Add(It.Is<User>(y => y == user)), Times.Once);
usersContextMock.Verify(x => x.SaveChanges(), Times.Once);
```

Same apporach should be used for _Remove_ function.

**Comment by DiscoDancer** [comment]
@MichalJankowskii  hello, thanks for tool, I've been using it with pleasure. Where can I find more examples like you posted in comment? I don't see them in this repository.

**Comment by kennymartinez** [comment]
I'm following this example and getting the No database provider error. Is there another example I can use as reference?

**Comment by MichalJankowskii** [comment]
In the repository, there is the file with examples - [UsersServiceTest.cs](https://github.com/MichalJankowskii/Moq.EntityFrameworkCore/blob/master/src/Moq.EntityFrameworkCore.Examples/UsersServiceTest.cs). I added mentioned test so you can run it locally.
