### ISSUE TITLE
Add sample usage of SetupAdd method

### ISSUE THREAD

**Issue by nanotaboada** [MichalJankowskii/Moq.EntityFrameworkCore#34]
The [test file](https://github.com/MichalJankowskii/Moq.EntityFrameworkCore/blob/master/src/Moq.EntityFrameworkCore.Examples/UsersServiceTest.cs) provided as documentation does not include any sample usage of the `SetupAdd` method.

Would it be possible to add some examples?
A desirable test case could be:

Sample Implementation
```
var foobar = new Foobar();
_foobarContext.Foobars.Add(foobar);
await _foobarContext.SaveChangesAsync();
```

Sample Test
```
// Arrange
var context = new Mock<FoobarContext>();
// context.SetupAdd()

// Assert
context.Verify(c => c.Add(It.IsAny<Foobar>()), Times.Exactly(1));
context.Verify(c => c.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Exactly(1));
```

**Comment by MichalJankowskii** [comment]
I added an example that should support your case [UsersServiceTest.cs](https://github.com/MichalJankowskii/Moq.EntityFrameworkCore/blob/master/src/Moq.EntityFrameworkCore.Examples/UsersServiceTest.cs).

Please check if it works for you.

**Comment by nanotaboada** [comment]
Thanks much!
