### ISSUE TITLE
Where with EF.Functions crashes

### ISSUE THREAD

**Issue by rogerfar** [MichalJankowskii/Moq.EntityFrameworkCore#41]
Would it be possible to mock calls the EF.Functions when they are used in linq statements?

For example:
```
var instances = await dataContext.Instances.Where(m => EF.Functions.ILike(hostname, $"{m.Url}%")).ToListAsync(cancellationToken: cancellationToken);
```

Results in:
```
The 'ILike' method is not supported because the query has switched to client-evaluation. This usually happens when the arguments to the method cannot be translated to server. Rewrite the query to avoid client evaluation of arguments so that method can be translated to server.
```

**Comment by MichalJankowskii** [comment]
Hi @rogerfar,

It would be best if you considered the approach in your app. Testing with the "in-memory db" approach has this limitation. 

That is why some tests need to be run in an environment that involves real DB.

You can read more here:  [Testing EF Core Applications](https://learn.microsoft.com/en-us/ef/core/testing/)
