### ISSUE TITLE
Argument expression is not valid

### ISSUE THREAD

**Issue by thedwillis** [MichalJankowskii/Moq.EntityFrameworkCore#9]
When attempting to use the library I'm encountering an ArgumentException with the message of `Argument expression is not valid`. I've been through the samples you've provided and I can't see what I've done wrong.

My unit test looks like:
`[Fact]
        public async void LockoutSeafarer_NotFound() {
            //ARRANGE
            var seafarers = new List<Seafarer> {
                SeafarerFactory.BuildCurrent(new Workspace(), RankFactory.BuildDefault())
            };

            var mockContext = new Mock<SeaComplyDbContext>();

            mockContext.Setup(x => x.Seafarers).ReturnsDbSet(seafarers);

            var sut = new SeafarerDataService(mockContext.Object);

            //ACT
            await sut.LockoutSeafarer(1);

            //ASSERT
            mockContext.VerifyGet(x => x.Seafarers, Times.Exactly(1));
        }`

and the function I am calling is:
`public async Task LockoutSeafarer(int seafarerId) {
            var seafarer = await Context.Seafarers.Where(s => s.Id == seafarerId).SingleOrDefaultAsync();

            if (seafarer == null) return;

            seafarer.LastUpdated = DateTime.UtcNow;
            seafarer.Enabled = false;
        }`

The line that is throwing the error is `var seafarer = await Context.Seafarers.Where(s => s.Id == seafarerId).SingleOrDefaultAsync();`

The only thing I am concerned about is that the Seafarer object is quite complex (lots of relationships), but outside of the unit test the code all runs fine.

I can confirm that I am using netcoreapp3.0 framework, EF core 3.0.0, and Moq 4.10.1.

Thanks for any help, and for making this awesome lib!

**Comment by MichalJankowskii** [comment]
Are you able to provide test that will reproduce your case?

**Comment by thedwillis** [comment]
I've decided to take a different approach, sorry for the bother.
